# Generated by Django 3.0.8 on 2020-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200903_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='heighest_bid',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='username',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='listing_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='creator_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
