# Generated by Django 3.0.8 on 2020-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200923_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator_id',
            field=models.IntegerField(),
        ),
    ]
