# Generated by Django 3.0.8 on 2020-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201004_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
