# Generated by Django 3.0.8 on 2020-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listing_title', models.CharField(max_length=64)),
            ],
        ),
    ]
